### ISSUE TITLE
Languages Pie Chart Angular

### ISSUE THREAD

**Issue by nathanafox-us** [SergeantFox234/Software_Portfolio#2]
## Problem
To prove our skill at coding and problem solving, lets create a custom Angular component for displaying a pie chart.

## Solution
There is already a component that has ```@input() languages:GithubLanguages[]```. Complete this component for the Github Cards.

## Todo:
- [x] Languages Wheel displays a donut that is proportional to the languages used
- [x] Languages use the same color for whole page (maybe we can have it pick a new one on reload)
- [x] There is a legend next to the wheel denoting which color is which language, and the exact % to 2 decimal places
