### ISSUE TITLE
Inquiries Page

### ISSUE THREAD

**Issue by nathanafox-us** [SergeantFox234/Software_Portfolio#3]
## New Feature
The Inquiries page is a page for sending me any questions.

## Todo:
- [ ] Inquiry Form
   - [ ] Checkbox for whether a response is requested
   - [ ] Response email (if response requested)
   - [ ] Type of comment checkbox
   - [ ] Comment field textbox
   - [ ] Send button
   - [ ] Clear button
   - [ ] Undo/Redo button
- [ ] The completed form is sent to me as an e-mail
