### ISSUE TITLE
Products Page

### ISSUE THREAD

**Issue by nathanafox-us** [SergeantFox234/Software_Portfolio#4]
## New Feature
The products page is a page that lists services I am readily offering. These services currently include:
- phone apps
- websites
- small embedded devices
- more complex, custom solutions

and they range in price depending on complexity from:
- simple: $10-$200
- complex: $400-$2000
- challenging: $2000+

## Todo:
- [ ] Section 1: Summary
- [ ] Section 2: Simple service examples
- [ ] Section 3: Custom service solutions
- [ ] Section 4: Service pricing calculator
